<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net48;net8.0</TargetFrameworks>
    <RootNamespace>ADBLogin.Core</RootNamespace>
    <AssemblyName>ADBLogin.Core</AssemblyName>
    <OutputType>Library</OutputType>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="Leaf.xNet">
      <HintPath>..\Leaf.xNet.dll</HintPath>
    </Reference>
    <Reference Include="WebDriver">
      <HintPath>..\WebDriver.dll</HintPath>
    </Reference>
    <Reference Include="HtmlAgilityPack">
      <HintPath>..\HtmlAgilityPack.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
